// React/src/components/DropDownList/DropDownList.tsx
import {
  useCallback, useEffect, useReducer, useRef, useState,
} from 'react';
import DropDownBox, { type DropDownBoxRef, type DropDownBoxTypes } from 'devextreme-react/drop-down-box';
import TreeList, {
  Column, Lookup, RemoteOperations, Scrolling, Selection, type TreeListRef, type TreeListTypes,
} from 'devextreme-react/tree-list';
import { type DataSource } from 'devextreme-react/common/data';
import {
  FIRST_ROW_KEY, applySearchFilter, isSearchIncomplete, lookupStore,
} from '../../service';
import { selectionReducer } from './selectionReducer';

interface DropDownListProps<T> {
  selectedRowKey: number;
  dataSource: DataSource;
  dropDownBoxDataSource: DataSource;
  searchTimeout?: number;
  displayExpr?: ((item: T) => string) | undefined;
  searchExprValue: string | string[];
}

export default function DropDownList<T>({
  selectedRowKey,
  dataSource,
  dropDownBoxDataSource,
  searchTimeout = 1000,
  displayExpr,
  searchExprValue,
}: DropDownListProps<T>): JSX.Element {
  const [selection, dispatch] = useReducer(selectionReducer, {
    dropDownValue: selectedRowKey,
    selectedRowKeys: [selectedRowKey],
    focusedRowKey: selectedRowKey,
  });

  const [dropDownBoxOpened, setDropDownBoxOpened] = useState(false);

  const treeListRef = useRef<TreeListRef>(null);
  const dropDownBoxRef = useRef<DropDownBoxRef>(null);

  const searchTimerIdRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const hasLoadedItemsRef = useRef(false);
  const listFirstLoadCompletedRef = useRef(false);

  useEffect(() => {
    function changedHandler(): void {
      requestAnimationFrame(() => {
        hasLoadedItemsRef.current = !!dataSource.items().length;
        if (hasLoadedItemsRef.current && !selection.focusedRowKey) {
          const items = dataSource.items();
          dispatch({ type: 'SET_FOCUSED_KEY', key: items[0].key });
        }
      });
    }

    dataSource.on('changed', changedHandler);

    changedHandler();

    return () => {
      dataSource.off('changed', changedHandler);
    };
  }, [dataSource, selection.focusedRowKey]);

  const focusInput = useCallback((): void => {
    setTimeout(() => {
      dropDownBoxRef.current?.instance().focus();
    });
  }, [dropDownBoxRef]);

  const onInput = useCallback((e: DropDownBoxTypes.InputEvent): void => {
    if (searchTimerIdRef.current) clearTimeout(searchTimerIdRef.current);

    const instance = e.component;
    if (!dropDownBoxOpened) setDropDownBoxOpened(true);

    if (isSearchIncomplete(instance)) {
      const text = instance.option('text');
      if (text) {
        searchTimerIdRef.current = setTimeout(() => {
          applySearchFilter(text, searchExprValue, dataSource);
        }, searchTimeout);
      } else {
        dataSource.filter(null);
      }
      focusInput();
    }
  }, [searchTimerIdRef, dropDownBoxOpened, searchExprValue, dataSource, searchTimeout]);

  const onOpened = useCallback((e: DropDownBoxTypes.OpenedEvent): void => {
    const treeListInstance = treeListRef.current?.instance();
    const dropDownBox = e.component;

    function handleOptionChanged(args: TreeListTypes.OptionChangedEvent): void {
      const list = args.component;
      const triggerCondition = listFirstLoadCompletedRef.current
        ? args.name === 'openTrigger'
        : args.name === 'focusedRowKey' || args.name === 'focusedColumnIndex';

      if (triggerCondition) {
        list.off('optionChanged', handleOptionChanged);
        requestAnimationFrame(() => {
          list.focus();
          list.option('openTrigger', 'closed');
        });
      }
    }

    treeListInstance?.on('optionChanged', handleOptionChanged);

    if (listFirstLoadCompletedRef.current) {
      treeListInstance?.option('openTrigger', 'opened');
    }

    const { text, value: dropDownValue } = dropDownBox.option();
    const dropDownDisplayValue = dropDownBox.option('displayValue') as string[] | undefined;
    const isTextEqualToDisplayValue = text === dropDownDisplayValue?.[0];
    const shouldClearSelection = (dropDownValue && !text) || !isTextEqualToDisplayValue;
    if (shouldClearSelection) {
      dispatch({ type: 'RESET' });
      treeListInstance?.pageIndex(0).then(() => {
        treeListInstance?.option('focusedRowIndex', 0);
        dispatch({ type: 'SET_FOCUSED_KEY', key: FIRST_ROW_KEY });
        focusInput();
      }).catch(() => {});
    }
  }, [focusInput, listFirstLoadCompletedRef, treeListRef]);

  const onOptionChanged = useCallback((e: DropDownBoxTypes.OptionChangedEvent): void => {
    if (e.name === 'text' && !e.value && listFirstLoadCompletedRef.current) {
      treeListRef.current?.instance().pageIndex(0).then(() => {
        treeListRef.current?.instance().option('focusedRowIndex', 0);
        dispatch({ type: 'SET_FOCUSED_KEY', key: FIRST_ROW_KEY });
      }).catch(() => {});
    }
  }, []);

  const onValueChanged = useCallback((e: DropDownBoxTypes.ValueChangedEvent): void => {
    if (searchTimerIdRef.current !== null) {
      clearTimeout(searchTimerIdRef.current);
      searchTimerIdRef.current = null;
    }
    dispatch({ type: 'SELECT_VALUE', value: e.value ?? null });
    if (e.value) {
      setDropDownBoxOpened(false);
    }
  }, [searchTimerIdRef]);

  const onKeyDown = useCallback((e: DropDownBoxTypes.KeyDownEvent): void => {
    if (e.event?.originalEvent?.key !== 'ArrowDown') return;
    const treeListInstance = treeListRef.current?.instance();
    if (!dropDownBoxOpened) {
      setDropDownBoxOpened(true);
    } else if (treeListInstance) {
      treeListInstance.focus();
    }
  }, [dropDownBoxOpened]);

  const onClosed = useCallback((e: DropDownBoxTypes.ClosedEvent): void => {
    const treeListInstance = treeListRef.current?.instance();
    const dropDownBox = e.component;
    const text = dropDownBox.option('text');
    const dropDownDisplayValue = (dropDownBox.option('displayValue') as string[] | undefined)?.[0];
    const resetValue = text && text !== dropDownDisplayValue;

    if (!hasLoadedItemsRef.current) {
      dispatch({ type: 'SELECT_VALUE', value: null });
      dataSource.filter(null);
      dataSource.load().catch(() => {});
    }

    if (resetValue && !selection.selectedRowKeys.length && treeListInstance) {
      const firstKey = treeListInstance.getKeyByRowIndex(0) as number;
      dispatch({ type: 'SELECT_VALUE', value: firstKey });
    }
  }, [selection.selectedRowKeys.length, dataSource]);

  const treeListOnContentReady = useCallback((e: TreeListTypes.ContentReadyEvent): void => {
    if (!listFirstLoadCompletedRef.current) {
      listFirstLoadCompletedRef.current = true;
      e.component.option('openTrigger', 'opened');
    }
  }, [listFirstLoadCompletedRef]);

  const treeListOnKeyDown = useCallback((e: TreeListTypes.KeyDownEvent): void => {
    if (e.event?.key === 'Enter') {
      dispatch({ type: 'SELECT_FOCUSED_ROW' });
      focusInput();
    }
  }, []);

  const onFocusedRowChanged = useCallback((e: TreeListTypes.FocusedRowChangedEvent): void => {
    dispatch({ type: 'SET_FOCUSED_KEY', key: (e.row?.key as number) ?? null });
  }, []);

  const onSelectionChanged = useCallback((e: TreeListTypes.SelectionChangedEvent): void => {
    if (!listFirstLoadCompletedRef.current || !e.selectedRowKeys.length) return;
    dispatch({ type: 'SELECT_ROW', keys: e.selectedRowKeys as number[] });
    focusInput();
  }, []);

  const treeListRender = useCallback(() => (
    <TreeList
      ref={treeListRef}
      dataSource={dataSource}
      hasItemsExpr="Has_Items"
      parentIdExpr="Task_Parent_ID"
      columnAutoWidth
      wordWrapEnabled
      showBorders
      height={400}
      width="100%"
      focusedRowEnabled
      focusedRowKey={selection.focusedRowKey}
      selectedRowKeys={selection.selectedRowKeys}
      onContentReady={treeListOnContentReady}
      onKeyDown={treeListOnKeyDown}
      onFocusedRowChanged={onFocusedRowChanged}
      onSelectionChanged={onSelectionChanged}
    >
      <RemoteOperations filtering sorting grouping />
      <Selection mode="single" />
      <Scrolling mode="virtual" />
      <Column dataField="Task_ID" />
      <Column dataField="Task_Assigned_Employee_ID" caption="Employee" minWidth={120}>
        <Lookup dataSource={lookupStore} valueExpr="ID" displayExpr="Name" />
      </Column>
      <Column dataField="Task_Subject" width={300} />
      <Column dataField="Task_Start_Date" caption="Start Date" dataType="date" />
      <Column dataField="Task_Status" caption="Status" />
      <Column dataField="Task_Due_Date" caption="Due Date" dataType="date" />
    </TreeList>
  ), [
    selection.focusedRowKey,
    selection.selectedRowKeys,
    treeListOnContentReady,
    treeListOnKeyDown,
    onFocusedRowChanged,
    onSelectionChanged,
  ]);

  return (
    <DropDownBox
      ref={dropDownBoxRef}
      placeholder="Select a value..."
      showClearButton
      width="40vw"
      value={selection.dropDownValue}
      acceptCustomValue
      openOnFieldClick={false}
      valueChangeEvent=""
      valueExpr="Task_ID"
      dataSource={dropDownBoxDataSource}
      displayExpr={displayExpr}
      opened={dropDownBoxOpened}
      onInput={onInput}
      onOpened={onOpened}
      onOptionChanged={onOptionChanged}
      onValueChanged={onValueChanged}
      onKeyDown={onKeyDown}
      onClosed={onClosed}
      onOpenedChange={setDropDownBoxOpened}
      contentRender={treeListRender}
    />
  );
}

// Vue/src/components/DropDownList.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import type { DataSource } from 'devextreme-vue/common/data';
import DxDropDownBox from 'devextreme-vue/drop-down-box';
import type { DxDropDownBoxTypes } from 'devextreme-vue/drop-down-box';
import {
  DxTreeList,
  DxColumn,
  DxLookup,
  DxRemoteOperations,
  DxScrolling,
  DxSelection,
  type DxTreeListTypes,
} from 'devextreme-vue/tree-list';
import {
  type Task,
  FIRST_ROW_KEY,
  applySearchFilter,
  isSearchIncomplete,
  lookupStore,
} from '@/service';

const props = defineProps<{
  selectedRowKey: number;
  dataSource: DataSource;
  dropDownBoxDataSource: DataSource;
  searchTimeout?: number;
  displayExpr?: ((item: Task) => string) | undefined;
  searchExprValue: string | string[];
}>();

const searchTimeoutValue = computed(() => props.searchTimeout ?? 1000);

const treeListRef = ref<DxTreeList | null>(null);
const dropDownBoxRef = ref<DxDropDownBox | null>(null);

const value = ref<number | null>(props.selectedRowKey);
const dropDownBoxOpened = ref(false);
const selectedRowKeys = ref<number[]>([props.selectedRowKey]);
const focusedRowKey = ref<number | null>(props.selectedRowKey);

let searchTimerId: ReturnType<typeof setTimeout> | null = null;
let hasLoadedItems = false;
let listFirstLoadCompleted = false;

function changedHandler(): void {
  requestAnimationFrame(() => {
    hasLoadedItems = !!props.dataSource.items().length;
    if (hasLoadedItems && !focusedRowKey.value) {
      const items = props.dataSource.items();
      if (items.length) focusedRowKey.value = items[0].key as number;
    }
  });
}

onMounted(() => {
  props.dataSource.on('changed', changedHandler);
  changedHandler();
});

onUnmounted(() => {
  props.dataSource.off('changed', changedHandler);
});

watch(
  () => props.displayExpr,
  (newVal, oldVal) => {
    if (oldVal !== undefined) {
      dropDownBoxRef.value?.instance?.repaint();
    }
  },
);

function focusInput(): void {
  setTimeout(() => {
    dropDownBoxRef.value?.instance?.focus();
  });
}

function onInput(e: DxDropDownBoxTypes.InputEvent): void {
  if (searchTimerId) clearTimeout(searchTimerId);

  const instance = e.component;
  if (!dropDownBoxOpened.value) dropDownBoxOpened.value = true;

  if (isSearchIncomplete(instance)) {
    const text = instance.option('text');
    if (text) {
      searchTimerId = setTimeout(() => {
        applySearchFilter(text, props.searchExprValue, props.dataSource);
      }, searchTimeoutValue.value);
    } else {
      props.dataSource.filter(null);
    }
    focusInput();
  }
}

function onOpened(e: DxDropDownBoxTypes.OpenedEvent): void {
  const treeListInstance = treeListRef.value?.instance;
  const dropDownBox = e.component;

  function handleOptionChanged(args: DxTreeListTypes.OptionChangedEvent): void {
    const list = args.component;
    const triggerCondition = listFirstLoadCompleted
      ? args.name === 'openTrigger'
      : args.name === 'focusedRowKey' || args.name === 'focusedColumnIndex';

    if (triggerCondition) {
      list.off('optionChanged', handleOptionChanged);
      requestAnimationFrame(() => {
        list.focus();
        list.option('openTrigger', 'closed');
      });
    }
  }

  treeListInstance?.on('optionChanged', handleOptionChanged);

  if (listFirstLoadCompleted) {
    treeListInstance?.option('openTrigger', 'opened');
  }

  const { text, value: dropDownValue } = dropDownBox.option();
  const displayValue = dropDownBox.option('displayValue') as
    | string[]
    | undefined;
  const isTextEqualToDisplayValue = text === displayValue?.[0];
  const shouldClearSelection =
    (dropDownValue && !text) || !isTextEqualToDisplayValue;

  if (shouldClearSelection) {
    selectedRowKeys.value = [];
    treeListInstance
      ?.pageIndex(0)
      .then(() => {
        treeListInstance?.option('focusedRowIndex', 0);
        focusedRowKey.value = FIRST_ROW_KEY;
        focusInput();
      })
      .catch(() => {});
  }
}

function onOptionChanged(e: DxDropDownBoxTypes.OptionChangedEvent): void {
  if (e.name === 'text' && !e.value && listFirstLoadCompleted) {
    const treeListInstance = treeListRef.value?.instance;
    treeListInstance
      ?.pageIndex(0)
      .then(() => {
        treeListInstance?.option('focusedRowIndex', 0);
        focusedRowKey.value = FIRST_ROW_KEY;
      })
      .catch(() => {});
  }
}

function onValueChanged(e: DxDropDownBoxTypes.ValueChangedEvent): void {
  if (searchTimerId !== null) {
    clearTimeout(searchTimerId);
    searchTimerId = null;
  }
  value.value = e.value ?? null;
  if (e.value) {
    dropDownBoxOpened.value = false;
  }
}

function onKeyDown(e: DxDropDownBoxTypes.KeyDownEvent): void {
  if (e.event?.originalEvent?.key !== 'ArrowDown') return;
  const treeListInstance = treeListRef.value?.instance;
  if (!dropDownBoxOpened.value) {
    dropDownBoxOpened.value = true;
  } else if (treeListInstance) {
    treeListInstance.focus();
  }
}

function onClosed(e: DxDropDownBoxTypes.ClosedEvent): void {
  const treeListInstance = treeListRef.value?.instance;
  const dropDownBox = e.component;
  const text = dropDownBox.option('text');
  const displayValue = (
    dropDownBox.option('displayValue') as string[] | undefined
  )?.[0];
  const resetValue = text && text !== displayValue;

  if (!hasLoadedItems) {
    value.value = null;
    selectedRowKeys.value = [];
    props.dataSource.filter(null);
    props.dataSource.load().catch(() => {});
  }

  if (resetValue && !selectedRowKeys.value.length && treeListInstance) {
    const firstKey = treeListInstance.getKeyByRowIndex(0) as number;
    value.value = firstKey;
    selectedRowKeys.value = [firstKey];
    focusedRowKey.value = firstKey;
  }
}

function treeListOnContentReady(e: DxTreeListTypes.ContentReadyEvent): void {
  if (!listFirstLoadCompleted) {
    listFirstLoadCompleted = true;
    e.component.option('openTrigger', 'opened');
  }
}

function treeListOnKeyDown(e: DxTreeListTypes.KeyDownEvent): void {
  if (e.event?.key === 'Enter' && focusedRowKey.value) {
    value.value = focusedRowKey.value;
    selectedRowKeys.value = [focusedRowKey.value];
    focusInput();
  }
}

function onSelectionChanged(e: DxTreeListTypes.SelectionChangedEvent): void {
  if (!listFirstLoadCompleted || !e.selectedRowKeys.length) return;
  const keys = e.selectedRowKeys as number[];
  value.value = keys[0];
  focusInput();
}
</script>

<template>
  <DxDropDownBox
    ref="dropDownBoxRef"
    placeholder="Select a value..."
    width="40vw"
    value-expr="Task_ID"
    value-change-event=""
    :value="value"
    :data-source="dropDownBoxDataSource"
    :display-expr="displayExpr"
    :show-clear-button="true"
    :accept-custom-value="true"
    :open-on-field-click="false"
    v-model:opened="dropDownBoxOpened"
    @value-changed="onValueChanged"
    @option-changed="onOptionChanged"
    @key-down="onKeyDown"
    @input="onInput"
    @opened="onOpened"
    @closed="onClosed"
  >
    <template #content>
      <DxTreeList
        ref="treeListRef"
        height="400"
        width="100%"
        has-items-expr="Has_Items"
        parent-id-expr="Task_Parent_ID"
        :data-source="dataSource"
        :column-auto-width="true"
        :word-wrap-enabled="true"
        :show-borders="true"
        :focused-row-enabled="true"
        v-model:focused-row-key="focusedRowKey"
        v-model:selected-row-keys="selectedRowKeys"
        @content-ready="treeListOnContentReady"
        @key-down="treeListOnKeyDown"
        @selection-changed="onSelectionChanged"
      >
        <DxRemoteOperations
          :filtering="true"
          :sorting="true"
          :grouping="true"
        />
        <DxSelection mode="single"/>
        <DxScrolling mode="virtual"/>
        <DxColumn data-field="Task_ID"/>
        <DxColumn
          data-field="Task_Assigned_Employee_ID"
          caption="Employee"
          :min-width="120"
        >
          <DxLookup
            :data-source="lookupStore"
            value-expr="ID"
            display-expr="Name"
          />
        </DxColumn>
        <DxColumn
          data-field="Task_Subject"
          :width="300"
        />
        <DxColumn
          data-field="Task_Start_Date"
          caption="Start Date"
          data-type="date"
        />
        <DxColumn
          data-field="Task_Status"
          caption="Status"
        />
        <DxColumn
          data-field="Task_Due_Date"
          caption="Due Date"
          data-type="date"
        />
      </DxTreeList>
    </template>
  </DxDropDownBox>
</template>
